version: "2"

services:
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
    logging:
      options:
        max-size: 50m
  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5001:5001"
      - "8889:8889"
      - "8890:8890"
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    depends_on:
      - elasticsearch
    logging:
      options:
        max-size: 50m
  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    logging:
      options:
        max-size: 50m
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    volumes:
      - ./grafana/data/:/var/lib/grafana
    logging:
      options:
        max-size: 50m