filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

filebeat.config.inputs:
  enabled: true
  path: ${path.config}/inputs/*.yml
  reload.enabled: true
  reload.period: 10s

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false

logging.level: debug
logging.to_stderr: true

setup:
  template.enabled: true
  ilm.enabled: true
  template.name: "filebeat"
  template.pattern: "filebeat"

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
# index: "clickup_daily_import"
# pipeline: "clickup_daily_import-pipeline"
#output.console:
#  enabled: true
