filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

filebeat.config.inputs:
  enabled: true
  path: /usr/share/filebeat/inputs/*.yml
  reload.enabled: true
  reload.period: 10s

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: "http://elasticsearch:9200"
